### PR TITLE
Fix PSL1GHT build

### PR DESCRIPTION
**Pull request by crystalct**
Using `-O3` gcc optimization, build fail with:
```
../../burn/drv/sega/d_segas32.cpp: In function 'INT32 DrvFrame()':
../../burn/drv/sega/d_segas32.cpp:4424:1: error: could not split insn
 }
 ^
(insn:TI 2537 2553 2555 (set (reg/v:TI 6 6 [orig:1058 clipin ] [1058])
        (mem/c:TI (plus:DI (reg/f:DI 1 1)
                (reg:DI 16 16 [2411])) [0  S16 A128])) "../../burn/drv/sega/d_segas32.cpp":3648 501 {*movti_ppc64}
     (nil))
../../burn/drv/sega/d_segas32.cpp:4424:1: internal compiler error: in final_scan_insn, at final.c:3025
```

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Hmmmm again, are you sure it's the right call ? You'll be slowing down the whole core for the purpose of building 1 driver (that is probably not even running full speed on ps3 anyway ?).

**Comment by crystalct** [comment]
Rarely i seen -O3 optimization in PSL1GHT (and also in old SDK) projects. I'm not sure about a real optimization better -O2 to -O3, but it could be possible. Do you have advices abit to compile only one (or some) source with -O2?

**Comment by barbudreadmon** [comment]
> Do you have advices about to compile only one (or some) source with -O2?

Hmmm there are hacks like this but i would certainly prefer figuring out why the compiler is having issues here. This error msg is confusing, line 4424 can't be the problem, meaning the problem is probably at line 3648 with `spritenum += 1 + draw_one_sprite(sprite, xoffs, yoffs, clipin, clipout);` ? Does it build if replaced by
```
spritenum += 1;
spritenum += draw_one_sprite(sprite, xoffs, yoffs, clipin, clipout);
```
?

**Comment by crystalct** [comment]
No.... same error

**Comment by crystalct** [comment]
It's some where inside` INT32 draw_one_sprite(UINT16 const *data, INT32 xoffs, INT32 yoffs, const clip_struct clipin, const clip_struct clipout)`

**Comment by barbudreadmon** [comment]
Indeed, apparently the psl1ght compiler dislike this code : 
```
	INT32 bank     = is_multi32 ?
					((BURN_ENDIAN_SWAP_INT16(data[3]) & 0x2000) >> 13) | ((BURN_ENDIAN_SWAP_INT16(data[3]) & 0x8000) >> 14) :
					((BURN_ENDIAN_SWAP_INT16(data[3]) & 0x0800) >> 11) | ((BURN_ENDIAN_SWAP_INT16(data[3]) & 0x4000) >> 13);
```

Putting everything on the same line seems to solve this ICE.

**Comment by crystalct** [comment]
I think it's ok, now.

**Comment by barbudreadmon** [comment]
That's not a fix, if it can't be solved in a proper way then i'll just remove segas32.cpp from the ps3 builds

**Comment by barbudreadmon** [comment]
or we set `-O2` for the whole psl1ght build, but i don't want to see hacky workarounds in game drivers

**Pull request closed without merging**
