### PR TITLE
Add some PSL1GHT/PS3 ifdefs

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
libretro-common stuff should be PRed to https://github.com/libretro/libretro-common first. Accepting local changes would be a bad idea since they'll potentially be deleted if i do a libretro-common sync (which i do from time to time).

**Comment by crystalct** [comment]
Could you make a libretro-common sync, please

**Comment by barbudreadmon** [comment]
who ? me ? i'm not a maintainer of those repos, you'll have to send them the PRs

**Comment by crystalct** [comment]
https://github.com/libretro/libretro-common is almost updated with last changes...
 https://github.com/libretro/RetroArch is already updated.
When both will be updated we can continue....
for now i delete this PR

**Comment by crystalct** [comment]
anyway i meant to resync fbneo libretro-common

**Comment by barbudreadmon** [comment]
done : https://github.com/libretro/FBNeo/commit/067b114e1036dc2d40effd19c91afdbb590d7ac7

**Pull request closed without merging**
