### PR TITLE
cleanup Emscripten build

### PR DESCRIPTION
**Pull request by ethanaobrien**
Emscripten should be built with `-O3`, not `-O2`

### CODE REVIEW

**Comment by barbudreadmon** [comment]
The current makefile builds msvc with `-O2` and anything else with `-O3` (including emscripten), so i don't understand the purpose of this PR ?

Furthermore, what do you mean by that ? Is there some kind of limitation preventing `-O2` to work with emscripten ?

**Comment by ethanaobrien** [comment]
>The current makefile builds msvc with -O2 and anything else with -O3 (including emscripten), so i don't understand the purpose of this PR ?

From the looks of it, it's the other way around, am I understanding this incorrectly?

>Furthermore, what do you mean by that ? Is there some kind of limitation preventing -O2 to work with emscripten ?

With the way emscripten works, a higher number results in higher compilation time, but faster runtime, which is a concern for running in the browser.
See https://emscripten.org/docs/optimizing/Optimizing-Code.html

**Comment by barbudreadmon** [comment]
>am I understanding this incorrectly?

Yes you are, i just confirmed from the [libretro buildbot](https://git.libretro.com/libretro/FBNeo/-/pipelines/215148) that everything is built using `-O3`.

>With the way emscripten works, a higher number results in higher compilation time, but faster runtime, which is a concern for running in the browser.

Then that's no different from all other platforms.

On a sidenote, using `-O3` is not something that should be done lightly. FinalBurn used to have quite a lot of crashes with it, and we spent weeks tracking and fixing all of those issues. I don't recommend sending that kind of PR without first being extremely familiar with a project's source code.

**Comment by ethanaobrien** [comment]
>Yes you are, i just confirmed from the [libretro buildbot](https://git.libretro.com/libretro/FBNeo/-/pipelines/215148) that everything is built using -O3.

Alright, I'll close this then

**Pull request closed without merging**
