### PR TITLE
Add load subsystem by parent option

### LINKED ISSUE #66: [Enhancement] Load subsystem by folder name
This is a request for an enhancement to the existing core:
Instead of requiring the --subsystem argument or loading games via the load subsystem menu in the Retroarch gui, add the possible core option of loading subsystem by parent folder name.  This is similar to how softlists can work with MAME and MESS in Retroarch so there is some precedent. 

Example:
Play burger time colecovision game with the command (and load subsystem by parent folder option enabled):
```
"...\path_to_program\retroarch.exe" -L "...\path_to_cores\cores\fbneo_libretro.dll" "...\path_to_game_files\cv\btime.zip"
```

FBNeo would then detect cv parent folder and load the cv subsystem argument, or default to the standard (no subsystem) loading if the folder name was not valid.

### PR DESCRIPTION
**Pull request by zach-morris**
Load subsystem based on parent directory name.  The parent folder names I used were based on naming in the common romset:
```
coleco
gamegear
megadriv
neocd
msx
pce
sg1000
spectrum
sgx
sms
tg16
```
This would close #66

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Seems to work, thank you for your contribution !

**Comment by paradadf** [comment]
megadriv? Not megadrive?
It would be useful to have alternatives also, like
colecovision
mastersystem
pcengine
supergrafx
zxspectrum

**Comment by barbudreadmon** [comment]
@paradadf this stuff was added as a workaround for RA's playlists, which are unable to deal with subsystems. Distro based on emulationstation can easily use the subsystem parameter.

**Comment by zach-morris** [comment]
> megadriv? Not megadrive?
> It would be useful to have alternatives also, like
> colecovision
> mastersystem
> pcengine
> supergrafx
> zxspectrum

Yes, not sure why those names were chosen as they were.  They follow [mame hash names](https://github.com/mamedev/mame/tree/master/hash).

**Comment by paradadf** [comment]
Ok, thanks for the explanation both!

**Pull request merged**
