### PR TITLE
fix PSL1GHT build

### PR DESCRIPTION
**Pull request by crystalct**
-O3 causes:
```
../../burn/drv/sega/d_segas32.cpp: In function 'INT32 DrvFrame()':
../../burn/drv/sega/d_segas32.cpp:4424:1: error: could not split insn
 }
 ^
(insn:TI 2537 2553 2555 (set (reg/v:TI 6 6 [orig:1058 clipin ] [1058])
        (mem/c:TI (plus:DI (reg/f:DI 1 1)
                (reg:DI 16 16 [2411])) [0  S16 A128])) "../../burn/drv/sega/d_segas32.cpp":3648 501 {*movti_ppc64}
     (nil))
../../burn/drv/sega/d_segas32.cpp:4424:1: internal compiler error: in final_scan_insn, at final.c:3025
```

And (for all platforms) `ifneq ($(STATIC_LINKING), 1)` should be wrong....

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Because of recent retroarch bump to lzma 2.0, static target must be built without 7z support, otherwise the build fails because of conflicts between frontend's 2.0 version and core's 1.0 version. Possible solution : bump FBNeo's lzma support to 2.0. Feel free if you are interested by that stuff.

Also, `ifneq ($(STATIC_LINKING), 1)` is right : on static builds, you aren't supposed to include in the core libraries that are already included in the frontend.

`could not split insn` looks like a compiler bug, maybe there is a better way to deal with this than using `-O2` globally (which will cause a drop in performance) ? In the first place is it happening consistently ? My experience with ICE errors is that they happened randomly.

**Comment by crystalct** [comment]
Strange.. i just compiled last retroarch build and i got:
```
ppu-g++ -o retroarch_psl1ght.elf -D__PSL1GHT__ -D__PS3__ -mcpu=cell -L. griffin/griffin.o -lretro_psl1ght -laudio -lrsx -lgcm_sys -lnet -lio -lsysutil -lsysmodule -lm -ljpgdec -lpngdec -llv2 -lnet -lnetctl -lsysfs
./libretro_psl1ght.a(zipfn.o):(.text._Z10ZipGetListPP8ZipEntryPi+0xf0): undefined reference to `SzArEx_GetFileNameUtf16'
./libretro_psl1ght.a(zipfn.o):(.text._Z10ZipGetListPP8ZipEntryPi+0x194): undefined reference to `SzArEx_GetFileNameUtf16'
./libretro_psl1ght.a(un7z.o):(.text._Z20_7z_search_crc_matchP9__7z_filejPKcibb+0x9c): undefined reference to `SzArEx_GetFileNameUtf16'
./libretro_psl1ght.a(un7z.o):(.text._Z20_7z_search_crc_matchP9__7z_filejPKcibb+0x200): undefined reference to `SzArEx_GetFileNameUtf16'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x25c): undefined reference to `LookToRead_CreateVTable'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x270): undefined reference to `LookToRead_Init'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x278): undefined reference to `CrcGenerateTable'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x284): undefined reference to `SzArEx_Init'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x2a0): undefined reference to `SzArEx_Open'
./libretro_psl1ght.a(un7z.o):(.text._Z13_7z_file_openPKcPP9__7z_file+0x3b8): undefined reference to `SzArEx_Free'
./libretro_psl1ght.a(un7z.o):(.text._Z14_7z_file_closeP9__7z_file+0x190): undefined reference to `SzArEx_Free'
./libretro_psl1ght.a(un7z.o):(.text._Z20_7z_file_cache_clearv+0xc0): undefined reference to `SzArEx_Free'
./libretro_psl1ght.a(un7z.o):(.text._Z19_7z_file_decompressP9__7z_filePvjPj+0x7c): undefined reference to `SzArEx_Extract'
make: *** [Makefile.psl1ght:83: retroarch_psl1ght.elf] Errore 1
```

wiith `ifneq ($(STATIC_LINKING), 1)`
If i choose a STATIC LINK.... what the compiler should statically to link if no sources .c are compiled?

**Comment by barbudreadmon** [comment]
> Strange.. i just compiled last retroarch build and i got

I repeat : static target must be built without 7z support, meaning `INCLUDE_7Z_SUPPORT = 0` must be added to https://github.com/libretro/FBNeo/blob/master/src/burner/libretro/Makefile#L215-L245 if ps3 is a static target

**Comment by crystalct** [comment]
I'm a bit confused....
If STATIC_LINKING = 1 this mena STATIC_LINK yes... right?
IF STATIC_LINKING is true, that mean that others sources need to be added? Or is the opposite?
Indipendently about 7z support?
For win platform that a DLL is created, i supposte a shared linking system..... why lib/z and zlib are compiled and linked inside dll?

**Comment by barbudreadmon** [comment]
Oops, you are absolutely right here, i did some mistake here

**Comment by crystalct** [comment]
Now is cleaner... STATIC LINK mean "it's present on Retraorch layer"
For win platform, that are shared, lib7z and zlib have to be compiled and added to dll. Perfect.

**Pull request closed without merging**
