### PR TITLE
Add New Features [taoenwen, tigerleap, agugu2000]

### PR DESCRIPTION
**Pull request by taoenwen**
- What's New -

[1] Add IPS Patch feature:
	- Identifies IPS Patch files in the "system/fbneo/ips/" directory and adds them to the [core options].
	- The selected IPS Patch files are enabled after restart.
	- Automatically exclude more than one IPS Patch with mandatory definition (#define) tags.

[2] Add RomData feature:
	- Identify the RomData files in the "system/fbneo/romdata/" directory and add them to the [core options].
	- The selected RomData will be enabled after restart.
	- When RomData encounters multiple selections, core options will randomly select one of them.

[3] Increase directory search scope of ROMs:
	- Perform additional searches in the [game directory] & [fbneo directory] for the following subdirectories:
	- "arc", "arcade", "romdata", "coleco", "colecovision", "gamegear", "megadriv", "megadrive", "genesis", "pce", "pcengine", "sg1000", "sgx", "supergrafx", "sms", "mastersystem", "spectrum", "zxspectrum", "tg16", "nes", "fds", "ngp", "chf", "channelf".

[4] Add Multi-Language support:
	- Simplified Chinese and Traditional Chinese have been added.
	- Multi-language is based on the front-end User UI language switching, the current design can be extended to a maximum of 12 languages in line with the Windows standalone version.
	- UGUI has expanded its font library to support English and other East Asian fonts.

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Thanks for this, and sorry i couldn't find the time to look into it, i have a few concerns though : 
- could you please remove the changes you did to `src/burner/burner.h` ? this file is in sync with upstream so i'd rather keep it exactly the same
- could you please document the new features in the readme at `src/burner/libretro/README.md` ?
- i'm not entirely sure i understand the part about multiple ips or romdata being enabled at the same time in core options and/or automatically excluding and/or choosing at random, i don't think that should be possible ? did you create 1 core option by patch/romdata with an enabled/disabled choice ? any reason you didn't create only 2 core options with multiple choices (1 patchset available = 1 choice, idem for romdata), so that it wouldn't be possible to enable several at once ?
- why was `dat` added to `info->valid_extensions` in `retro_get_system_info` ? `valid_extensions` only concerns romfile extensions.

**Comment by barbudreadmon** [comment]
Also, it is probably important to disable patches/romdatas when patched games aren't permitted (`bPatchedRomsetsEnabled` false), the retroachievements project forbid patched games and check that option before permitting retroachievements

**Comment by taoenwen** [comment]
Okay, I'll go refine those.

**Comment by taoenwen** [comment]
> Thanks for this, and sorry i couldn't find the time to look into it, i have a few concerns though :
> 
> * could you please remove the changes you did to `src/burner/burner.h` ? this file is in sync with upstream so i'd rather keep it exactly the same. if the different names are a matter of concern, i'd rather have those 2 files named romdata.cpp and ips_manager.cpp in the libretro port

done.
https://github.com/libretro/FBNeo/pull/1081/commits/500afbcfee6a378596958610f3c1149f93c56d4c

> * could you please document the new features in the readme at `src/burner/libretro/README.md` ?

yes.
https://github.com/libretro/FBNeo/pull/1081/commits/9e6e675ca563b0208d27a0fe52d472e317379593

> * i'm not entirely sure i understand the part about multiple ips or romdata being enabled at the same time in core options and/or automatically excluding and/or choosing at random, i don't think that should be possible ? did you create 1 core option by patch/romdata with an enabled/disabled choice ? any reason you didn't create only 2 core options with multiple choices (1 patchset available = 1 choice, idem for romdata), so that it wouldn't be possible to enable several patchset or romdata at once ? or am i wrong in thinking that only 1 patchset and/or 1 romdata should be enablable at once ?

The ips patch allows multiple iterations, but patches with the #define flag will have some memory manipulation, and repeated iterations at this point will cause confusion for the program, so the program checks for the presence of #define and ignores all subsequent patch files with the same flag.

romdata replaces the romdesc within the code with an external romdesc for customized gameplay. Listening to the suggestions of many users, romdata multi-selection means triggering the determination of randomly selecting a romdata, which is a better entertaining experience.

> * why was `dat` added to `info->valid_extensions` in `retro_get_system_info` ? `valid_extensions` only concerns romfile extensions.

Excluded.
https://github.com/libretro/FBNeo/pull/1081/commits/041d7420b4f3e063c6905d97943597670d02ea75

> Also, it is probably important to disable patches/romdatas when patched games aren't permitted (bPatchedRomsetsEnabled false), the [retroachievements project](https://retroachievements.org/) forbid patched games and check that this option is disabled before permitting retroachievements

done.
https://github.com/libretro/FBNeo/pull/1081/commits/998b0cb3a2fd0b8e06f87e3074554dd4b3e6d585

@barbudreadmon To this point, I would like to say thank you! For being able to read all of this.

**Comment by barbudreadmon** [comment]
Ok, i'll try to test all of this this week-end, thanks for the contribution :)

**Comment by taoenwen** [comment]
https://easyupload.io/r0m8mf

@barbudreadmon Here's a couple of materials available for testing, it may help if you're still looking for something to test, good luck with everything! (Only 7 days)

**Comment by barbudreadmon** [comment]
I finally got time to test this, and it instantly crashed when i tried loading a game :/

**Comment by barbudreadmon** [comment]
Now i'm getting this error when building : 
```
../../burner/libretro/libretro.cpp: In function 'int retro_dat_romset_path(const retro_game_info*)':
../../burner/libretro/libretro.cpp:2236:83: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
 2236 |         char szDatDir[MAX_PATH] = { 0 }, szRomset[128] = { 0 }, * pszTmp = strrchr(info->path, '.');
      |                                                                            ~~~~~~~^~~~~~~~~~~~~~~~~
      |                                                                                   |
      |                                                                                   const char*

```

**Comment by barbudreadmon** [comment]
Some early feedbacks : 
- the new font for error messages is cool, it's a lot more readable than the previous one.
- when i loaded a game, i noticed each of the romsets involved is searched at 55 different locations. I didn't understand the reason behind that new behavior, and i'm kinda worried since some android devices are known for arbitrarily closing the app if they deem the boot process as too long.
- i noticed some warnings about shadowed variables in romdata.cpp and ips_manager.cpp, i recommend fixing those since shadowed variables can lead to weird bugs.

I didn't test the romdata/ips features yet, hopefully i will do that this week-end.

**Comment by taoenwen** [comment]
First of all, thank you for taking the time to test it!

> * the new font for error messages is cool, it's a lot more readable than the previous one.

I'm glad you like the font too.

> * when i loaded a game, i noticed each of the romsets involved is searched at 55 different locations. I didn't understand the reason behind that new behavior, and i'm kinda worried since some android devices are known for arbitrarily closing the app if they deem the boot process as too long.

The original built-in ROMs search covered a small range of directories, so subdirectories including arcade | arc | romdata and consoles have been added;
After testing with some cheap Android set-top boxes (s905) and Android phones, there is hardly any prolonged read time to be found, as it is not traversing directories, but rather searching directionally in those directories, which consumes a very short amount of time (and exits if not searched);
The above has been tested and verified by many users, and also appears to be friendly to the requirement for ips to specify the drvname directory.
So, please don't worry about it.

> * i noticed some warnings about shadowed variables in romdata.cpp and ips_manager.cpp, i recommend fixing those since shadowed variables can lead to weird bugs.

The compilation warnings and shadow variables for the libretro.cpp, romdata.cpp & ips_manager.cpp are now all fixed, as well as testing the integrity of each feature after the fix.

> I didn't test the romdata/ips features yet, hopefully i will do that this week-end.

Thank you again for your time on this project and finally, I wish you all the best!

**Comment by taoenwen** [comment]
@barbudreadmon Hi,
Now that they have all made the required changes, please review them again when you have the time and thank you very much for your time spent on this project.

**Comment by barbudreadmon** [comment]
Ok, i'll merge this for now, there are a few things i'm concerned about and might re-evaluate in the future though : 
- The fact it checks dozens of subfolders, there is no apparent reason you'd ever want to check some "nes" subfolder for an arcade game you are trying to load, honestly that change seems entirely non-sensical to me and the problem i talked about (called ANR) can't be predicted just from cpu power.
- That whole "startup privileges" problem for romdata/patchsets is rather unclear for me. Do you have examples of games that would "break" if we persisted those choices between boots ? I'd rather not force users to go through some cumbersome additional steps every time they want to play their favorite patchsets/romdatas.

**Comment by taoenwen** [comment]
Hi, barbudreadmon
Thank you very much for your support and advice throughout this project, you have helped me to correct many potential problems that were not easy to spot.

> * The fact it checks dozens of subfolders, there is no apparent reason you'd ever want to check some "nes" subfolder for an arcade game you are trying to load, honestly that change seems entirely non-sensical to me and the problem i talked about (called ANR) can't be predicted just from cpu power.

On the point you mentioned, my starting point is based on the habits of some users, of course, if the user does not have the need for multiple catalogs, it is completely possible to eliminate this feature, I will not insist on this point.

> * That whole "startup privileges" problem for romdata/patchsets is rather unclear for me. Do you have examples of games that would "break" if we persisted those choices between boots ? I'd rather not force users to go through some cumbersome additional steps every time they want to play their favorite patchsets/romdatas.

First of all, IPS Patch/RomData does not cause other failures to occur;
Secondly, IPS Patch/RomData is an auxiliary function of the core and must be activated with the explicit intent of the user, otherwise it is, as I said, scrambling for activation privileges, so I may have misled you;
Finally, if users have some good suggestions or comments, I'll be back soon to maintain them.

I also benefited a lot from my work with you this time, and I am very happy to have had this pleasant experience, thank you very much!

**Comment by barbudreadmon** [comment]
>On the point you mentioned, my starting point is based on the habits of some users

Do you have a precise use-case for this ? It doesn't seem like something that would ever be useful in a "normal" usage through retroarch playlists, launchbox, emulationstation, ...

>scrambling for activation privileges

The meaning of that sentence is eluding me, could you better explain it ?

Btw, thanks for your work !

**Pull request merged**
