### PR TITLE
Fix Makefile for PSL1GHT

### PR DESCRIPTION
**Pull request by crystalct**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
if you feel like updating lib7z support to version 2.0 upstream, you are welcome ;)

**Comment by crystalct** [comment]
Hello again...
I can't compile Retroarch with lib7z version 2 on PSL1GHT because there isn't a lzma library (or a way to compile it).
I tired to compile FBNeo local lib7z with success, but it was necessary add this (in Makefile):
```
ifneq (,$(findstring psl1ght,$(platform)))
	$(AR) rcs $@ $(OBJS)
else
```
inside
```
$(TARGET): $(OBJS)
ifeq ($(STATIC_LINKING), 1)
ifeq ($(SPLIT_UP_LINK), 1)
	$(AR) rcs $@ $(foreach OBJS,$(OBJS),$(NEWLINE) $(AR) q $@ $(OBJS))
else
	$(AR) rcs $@ $(OBJS)
endif
else
ifeq ($(SPLIT_UP_LINK), 1)
	# Use a temporary file to hold the list of objects, as it can exceed windows shell command limits
	$(file >$@.in,$(OBJS))
	$(LD) $(LINKOUT)$@ $(SHARED) @$@.in $(LDFLAGS) $(LIBS)
	@rm $@.in
else
ifneq (,$(findstring psl1ght,$(platform)))
	$(AR) rcs $@ $(OBJS)
else
	$(LD) $(LINKOUT)$@ $(SHARED) $^ $(LDFLAGS) $(LIBS)
endif
endif
endif
```
`AR` is necessary to create a `.a` library but using `STATIC_LINKING = 0` wasn't possible.

**Comment by barbudreadmon** [comment]
Ok, i thought those lzma issues with static builds would be ok after i updated lzma in FBNeo with https://github.com/libretro/FBNeo/commit/5a0511ef6af7f468178ab5383efe2b0af5ad3d0c, but i guess that won't be the case. For now i disabled 7z again for ps3 with https://github.com/libretro/FBNeo/commit/50fdaf0f3949359e7b86f3822e93c36283984b6f .

**Comment by crystalct** [comment]
local support for PS3 works, just tested using:
```
STATIC_LINKING = 0
INCLUDE_7Z_SUPPORT = 1
```
but i anticipated this:

**Pull request merged**
