### PR TITLE
merger

### PR DESCRIPTION
**Pull request by dinkc64**

### CODE REVIEW

**Comment by barbudreadmon** [comment]
Erf, not a good idea, the libretro bot can't generate the header file, could you commit a working one ?

**Comment by dinkc64** [comment]
what file is it?

**Comment by barbudreadmon** [comment]
Most likely it broke the build, the file i'm talking about is driverlist.h

**Comment by dinkc64** [comment]
so even though the build is broke, can they still get the previous core? 
because I can't figure this git web sh*t out..... :/
p.s. sorry for causing this trouble.

**Comment by barbudreadmon** [comment]
I think some platform builds (wiiu ?) need all cores to build properly or they won't update any core at all.

**Comment by dinkc64** [comment]
I think it should be OK now, can you please check? (when it's done building)

**Pull request merged**
